[package]
name = "wasm-pack"
version = "0.1.0"
authors = ["Weiping Xiang <weiping.xiang@shopee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
